name: lemonade
description: Simple, typesafe, object-oriented library for data validation
version: 0.3.0
repository: https://github.com/uSlashVlad/lemonade

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  test: ^1.24.2
  very_good_analysis: ^4.0.0
